stages:
  ApplyHeuristics:
    do:
      always_changed: false
      cmd: bohr porcelain apply-heuristics --heuristic-group "${item.heuristic_group}"
        --dataset "${item.dataset}"
      deps:
      - cloned-bohr/heuristics/${item.heuristic_group}
      - cached-datasets/${item.dataset}.jsonl
      metrics: []
      outs:
      - runs/__heuristics/${item.dataset}/${item.heuristic_group}/heuristic_matrix.pkl
      params:
      - bohr.lock:
        - bohr_runtime_version
    foreach:
      berger_files__/bugginess/buggless_if_doc_extensions.py:
        dataset: berger_files
        heuristic_group: /bugginess/buggless_if_doc_extensions.py
      berger_files__/bugginess/conventional_commit_regex.py:
        dataset: berger_files
        heuristic_group: /bugginess/conventional_commit_regex.py
      berger_files__/bugginess/filemetrics/buggless_one_file.py:
        dataset: berger_files
        heuristic_group: /bugginess/filemetrics/buggless_one_file.py
      berger_files__/bugginess/fine_grained_changes_transformer_90.py:
        dataset: berger_files
        heuristic_group: /bugginess/fine_grained_changes_transformer_90.py
      berger_files__/bugginess/fix_keyword.py:
        dataset: berger_files
        heuristic_group: /bugginess/fix_keyword.py
      berger_files__/refactoring/keywords.py:
        dataset: berger_files
        heuristic_group: /refactoring/keywords.py
      levin_files__/bugginess/buggless_if_doc_extensions.py:
        dataset: levin_files
        heuristic_group: /bugginess/buggless_if_doc_extensions.py
      levin_files__/bugginess/conventional_commit_regex.py:
        dataset: levin_files
        heuristic_group: /bugginess/conventional_commit_regex.py
      levin_files__/bugginess/filemetrics/buggless_one_file.py:
        dataset: levin_files
        heuristic_group: /bugginess/filemetrics/buggless_one_file.py
      levin_files__/bugginess/fine_grained_changes_transformer_90.py:
        dataset: levin_files
        heuristic_group: /bugginess/fine_grained_changes_transformer_90.py
      levin_files__/bugginess/fix_keyword.py:
        dataset: levin_files
        heuristic_group: /bugginess/fix_keyword.py
      levin_files__/refactoring/keywords.py:
        dataset: levin_files
        heuristic_group: /refactoring/keywords.py
      manual_labels.herzig__/bugginess/buggless_if_doc_extensions.py:
        dataset: manual_labels.herzig
        heuristic_group: /bugginess/buggless_if_doc_extensions.py
      manual_labels.herzig__/bugginess/conventional_commit_regex.py:
        dataset: manual_labels.herzig
        heuristic_group: /bugginess/conventional_commit_regex.py
      manual_labels.herzig__/bugginess/filemetrics/buggless_one_file.py:
        dataset: manual_labels.herzig
        heuristic_group: /bugginess/filemetrics/buggless_one_file.py
      manual_labels.herzig__/bugginess/fine_grained_changes_transformer_90.py:
        dataset: manual_labels.herzig
        heuristic_group: /bugginess/fine_grained_changes_transformer_90.py
      manual_labels.herzig__/bugginess/fix_keyword.py:
        dataset: manual_labels.herzig
        heuristic_group: /bugginess/fix_keyword.py
      manual_labels.herzig__/refactoring/keywords.py:
        dataset: manual_labels.herzig
        heuristic_group: /refactoring/keywords.py
      mauczka_files__/bugginess/buggless_if_doc_extensions.py:
        dataset: mauczka_files
        heuristic_group: /bugginess/buggless_if_doc_extensions.py
      mauczka_files__/bugginess/conventional_commit_regex.py:
        dataset: mauczka_files
        heuristic_group: /bugginess/conventional_commit_regex.py
      mauczka_files__/bugginess/filemetrics/buggless_one_file.py:
        dataset: mauczka_files
        heuristic_group: /bugginess/filemetrics/buggless_one_file.py
      mauczka_files__/bugginess/fine_grained_changes_transformer_90.py:
        dataset: mauczka_files
        heuristic_group: /bugginess/fine_grained_changes_transformer_90.py
      mauczka_files__/bugginess/fix_keyword.py:
        dataset: mauczka_files
        heuristic_group: /bugginess/fix_keyword.py
      mauczka_files__/refactoring/keywords.py:
        dataset: mauczka_files
        heuristic_group: /refactoring/keywords.py
  CalculateMetrics:
    do:
      always_changed: false
      cmd: bohr porcelain run-metrics-and-analysis "${item.exp}" "${item.dataset}"
      deps:
      - runs/${item.task}/${item.exp}/${item.dataset}/heuristic_matrix.pkl
      - runs/${item.task}/${item.exp}/label_model.pkl
      - cached-datasets/${item.dataset}.jsonl
      metrics:
      - runs/${item.task}/${item.exp}/${item.dataset}/metrics.txt:
          cache: false
      outs:
      - runs/${item.task}/${item.exp}/${item.dataset}/analysis.json:
          cache: false
      - runs/${item.task}/${item.exp}/${item.dataset}/analysis.csv:
          cache: false
      params:
      - bohr.lock:
        - bohr_runtime_version
    foreach:
      all_heuristics_with_issues__berger_files:
        dataset: berger_files
        exp: all_heuristics_with_issues
        task: bugginess
      all_heuristics_with_issues__levin_files:
        dataset: levin_files
        exp: all_heuristics_with_issues
        task: bugginess
      all_heuristics_with_issues__manual_labels.herzig:
        dataset: manual_labels.herzig
        exp: all_heuristics_with_issues
        task: bugginess
      all_heuristics_with_issues__mauczka_files:
        dataset: mauczka_files
        exp: all_heuristics_with_issues
        task: bugginess
      refactoring_few_ref_heuristics__levin_files:
        dataset: levin_files
        exp: refactoring_few_ref_heuristics
        task: refactoring
      refactoring_few_ref_heuristics__manual_labels.herzig:
        dataset: manual_labels.herzig
        exp: refactoring_few_ref_heuristics
        task: refactoring
  ComputeRandomModelMetrics:
    do:
      always_changed: false
      cmd: bohr porcelain compute-random-model-metrics "${item.task}" "${item.dataset}"
      deps:
      - cached-datasets/${item.dataset}.jsonl
      metrics:
      - runs/${item.task}/random_model/${item.dataset}/metrics.txt:
          cache: false
      outs: []
      params:
      - bohr.lock:
        - bohr_runtime_version
    foreach:
      bugginess__berger_files:
        dataset: berger_files
        task: bugginess
      bugginess__manual_labels.herzig:
        dataset: manual_labels.herzig
        task: bugginess
      bugginess__mauczka_files:
        dataset: mauczka_files
        task: bugginess
      refactoring__manual_labels.herzig:
        dataset: manual_labels.herzig
        task: refactoring
  ComputeSingleHeuristicMetrics__bugginess:
    always_changed: false
    cmd: bohr porcelain compute-single-heuristic-metric bugginess
    deps:
    - cached-datasets/berger_files.jsonl
    - cached-datasets/manual_labels.herzig.jsonl
    - cached-datasets/mauczka_files.jsonl
    - cloned-bohr/heuristics//bugginess/buggless_if_doc_extensions.py
    - runs/__heuristics/berger_files//bugginess/buggless_if_doc_extensions.py/heuristic_matrix.pkl
    - runs/__heuristics/manual_labels.herzig//bugginess/buggless_if_doc_extensions.py/heuristic_matrix.pkl
    - runs/__heuristics/mauczka_files//bugginess/buggless_if_doc_extensions.py/heuristic_matrix.pkl
    - cloned-bohr/heuristics//bugginess/conventional_commit_regex.py
    - runs/__heuristics/berger_files//bugginess/conventional_commit_regex.py/heuristic_matrix.pkl
    - runs/__heuristics/manual_labels.herzig//bugginess/conventional_commit_regex.py/heuristic_matrix.pkl
    - runs/__heuristics/mauczka_files//bugginess/conventional_commit_regex.py/heuristic_matrix.pkl
    - cloned-bohr/heuristics//bugginess/filemetrics/buggless_one_file.py
    - runs/__heuristics/berger_files//bugginess/filemetrics/buggless_one_file.py/heuristic_matrix.pkl
    - runs/__heuristics/manual_labels.herzig//bugginess/filemetrics/buggless_one_file.py/heuristic_matrix.pkl
    - runs/__heuristics/mauczka_files//bugginess/filemetrics/buggless_one_file.py/heuristic_matrix.pkl
    - cloned-bohr/heuristics//bugginess/fine_grained_changes_transformer_90.py
    - runs/__heuristics/berger_files//bugginess/fine_grained_changes_transformer_90.py/heuristic_matrix.pkl
    - runs/__heuristics/manual_labels.herzig//bugginess/fine_grained_changes_transformer_90.py/heuristic_matrix.pkl
    - runs/__heuristics/mauczka_files//bugginess/fine_grained_changes_transformer_90.py/heuristic_matrix.pkl
    - cloned-bohr/heuristics//bugginess/fix_keyword.py
    - runs/__heuristics/berger_files//bugginess/fix_keyword.py/heuristic_matrix.pkl
    - runs/__heuristics/manual_labels.herzig//bugginess/fix_keyword.py/heuristic_matrix.pkl
    - runs/__heuristics/mauczka_files//bugginess/fix_keyword.py/heuristic_matrix.pkl
    - cloned-bohr/heuristics//refactoring/keywords.py
    - runs/__heuristics/berger_files//refactoring/keywords.py/heuristic_matrix.pkl
    - runs/__heuristics/manual_labels.herzig//refactoring/keywords.py/heuristic_matrix.pkl
    - runs/__heuristics/mauczka_files//refactoring/keywords.py/heuristic_matrix.pkl
    metrics: []
    outs:
    - runs/__single_heuristic_metrics/bugginess/berger_files//bugginess/buggless_if_doc_extensions.py/metrics.txt:
        cache: false
    - runs/__single_heuristic_metrics/bugginess/berger_files//bugginess/conventional_commit_regex.py/metrics.txt:
        cache: false
    - runs/__single_heuristic_metrics/bugginess/berger_files//bugginess/filemetrics/buggless_one_file.py/metrics.txt:
        cache: false
    - runs/__single_heuristic_metrics/bugginess/berger_files//bugginess/fine_grained_changes_transformer_90.py/metrics.txt:
        cache: false
    - runs/__single_heuristic_metrics/bugginess/berger_files//bugginess/fix_keyword.py/metrics.txt:
        cache: false
    - runs/__single_heuristic_metrics/bugginess/berger_files//refactoring/keywords.py/metrics.txt:
        cache: false
    - runs/__single_heuristic_metrics/bugginess/manual_labels.herzig//bugginess/buggless_if_doc_extensions.py/metrics.txt:
        cache: false
    - runs/__single_heuristic_metrics/bugginess/manual_labels.herzig//bugginess/conventional_commit_regex.py/metrics.txt:
        cache: false
    - runs/__single_heuristic_metrics/bugginess/manual_labels.herzig//bugginess/filemetrics/buggless_one_file.py/metrics.txt:
        cache: false
    - ? runs/__single_heuristic_metrics/bugginess/manual_labels.herzig//bugginess/fine_grained_changes_transformer_90.py/metrics.txt
      : cache: false
    - runs/__single_heuristic_metrics/bugginess/manual_labels.herzig//bugginess/fix_keyword.py/metrics.txt:
        cache: false
    - runs/__single_heuristic_metrics/bugginess/manual_labels.herzig//refactoring/keywords.py/metrics.txt:
        cache: false
    - runs/__single_heuristic_metrics/bugginess/mauczka_files//bugginess/buggless_if_doc_extensions.py/metrics.txt:
        cache: false
    - runs/__single_heuristic_metrics/bugginess/mauczka_files//bugginess/conventional_commit_regex.py/metrics.txt:
        cache: false
    - runs/__single_heuristic_metrics/bugginess/mauczka_files//bugginess/filemetrics/buggless_one_file.py/metrics.txt:
        cache: false
    - runs/__single_heuristic_metrics/bugginess/mauczka_files//bugginess/fine_grained_changes_transformer_90.py/metrics.txt:
        cache: false
    - runs/__single_heuristic_metrics/bugginess/mauczka_files//bugginess/fix_keyword.py/metrics.txt:
        cache: false
    - runs/__single_heuristic_metrics/bugginess/mauczka_files//refactoring/keywords.py/metrics.txt:
        cache: false
    params:
    - bohr.lock:
      - bohr_runtime_version
  ComputeSingleHeuristicMetrics__refactoring:
    always_changed: false
    cmd: bohr porcelain compute-single-heuristic-metric refactoring
    deps:
    - cached-datasets/manual_labels.herzig.jsonl
    - cloned-bohr/heuristics//bugginess/buggless_if_doc_extensions.py
    - runs/__heuristics/manual_labels.herzig//bugginess/buggless_if_doc_extensions.py/heuristic_matrix.pkl
    - cloned-bohr/heuristics//bugginess/conventional_commit_regex.py
    - runs/__heuristics/manual_labels.herzig//bugginess/conventional_commit_regex.py/heuristic_matrix.pkl
    - cloned-bohr/heuristics//bugginess/filemetrics/buggless_one_file.py
    - runs/__heuristics/manual_labels.herzig//bugginess/filemetrics/buggless_one_file.py/heuristic_matrix.pkl
    - cloned-bohr/heuristics//bugginess/fine_grained_changes_transformer_90.py
    - runs/__heuristics/manual_labels.herzig//bugginess/fine_grained_changes_transformer_90.py/heuristic_matrix.pkl
    - cloned-bohr/heuristics//bugginess/fix_keyword.py
    - runs/__heuristics/manual_labels.herzig//bugginess/fix_keyword.py/heuristic_matrix.pkl
    - cloned-bohr/heuristics//refactoring/keywords.py
    - runs/__heuristics/manual_labels.herzig//refactoring/keywords.py/heuristic_matrix.pkl
    metrics: []
    outs:
    - runs/__single_heuristic_metrics/refactoring/manual_labels.herzig//bugginess/buggless_if_doc_extensions.py/metrics.txt:
        cache: false
    - runs/__single_heuristic_metrics/refactoring/manual_labels.herzig//bugginess/conventional_commit_regex.py/metrics.txt:
        cache: false
    - runs/__single_heuristic_metrics/refactoring/manual_labels.herzig//bugginess/filemetrics/buggless_one_file.py/metrics.txt:
        cache: false
    - ? runs/__single_heuristic_metrics/refactoring/manual_labels.herzig//bugginess/fine_grained_changes_transformer_90.py/metrics.txt
      : cache: false
    - runs/__single_heuristic_metrics/refactoring/manual_labels.herzig//bugginess/fix_keyword.py/metrics.txt:
        cache: false
    - runs/__single_heuristic_metrics/refactoring/manual_labels.herzig//refactoring/keywords.py/metrics.txt:
        cache: false
    params:
    - bohr.lock:
      - bohr_runtime_version
  ComputeZeroModelMetrics:
    do:
      always_changed: false
      cmd: bohr porcelain compute-zero-model-metrics "${item.task}" "${item.dataset}"
      deps:
      - cached-datasets/${item.dataset}.jsonl
      metrics:
      - runs/${item.task}/zero_model/${item.dataset}/metrics.txt:
          cache: false
      outs: []
      params:
      - bohr.lock:
        - bohr_runtime_version
    foreach:
      bugginess__berger_files:
        dataset: berger_files
        task: bugginess
      bugginess__manual_labels.herzig:
        dataset: manual_labels.herzig
        task: bugginess
      bugginess__mauczka_files:
        dataset: mauczka_files
        task: bugginess
      refactoring__manual_labels.herzig:
        dataset: manual_labels.herzig
        task: refactoring
  FetchMultipleHeuristicOutputs:
    do:
      always_changed: false
      cmd: bohr porcelain combine-heuristics "${item.exp}" --dataset "${item.dataset}"
      deps:
      - runs/__heuristics/${item.dataset}
      metrics: []
      outs:
      - runs/${item.task}/${item.exp}/${item.dataset}/heuristic_matrix.pkl
      params:
      - bohr.lock:
        - experiments.${item.exp}.heuristics_classifier
      - bohr.lock:
        - bohr_runtime_version
    foreach:
      all_heuristics_with_issues__berger_files:
        dataset: berger_files
        exp: all_heuristics_with_issues
        task: bugginess
      all_heuristics_with_issues__levin_files:
        dataset: levin_files
        exp: all_heuristics_with_issues
        task: bugginess
      all_heuristics_with_issues__manual_labels.herzig:
        dataset: manual_labels.herzig
        exp: all_heuristics_with_issues
        task: bugginess
      all_heuristics_with_issues__mauczka_files:
        dataset: mauczka_files
        exp: all_heuristics_with_issues
        task: bugginess
      refactoring_few_ref_heuristics__levin_files:
        dataset: levin_files
        exp: refactoring_few_ref_heuristics
        task: refactoring
      refactoring_few_ref_heuristics__manual_labels.herzig:
        dataset: manual_labels.herzig
        exp: refactoring_few_ref_heuristics
        task: refactoring
  LoadDatasets:
    do:
      always_changed: false
      cmd: bohr porcelain load-dataset "${item}"
      deps: []
      metrics: []
      outs:
      - cached-datasets/${item}.jsonl
      - cached-datasets/${item}.jsonl.metadata.json:
          cache: false
      params:
      - bohr.lock:
        - bohr_runtime_version
    foreach:
    - berger_files
    - levin_files
    - manual_labels.herzig
    - mauczka_files
  PrepareDataset:
    do:
      always_changed: false
      cmd: bohr porcelain prepare-dataset "${item.exp}" "${item.dataset}"
      deps:
      - runs/${item.task}/${item.exp}/${item.dataset}/heuristic_matrix.pkl
      - runs/${item.task}/${item.exp}/label_model.pkl
      metrics: []
      outs:
      - runs/${item.task}/${item.exp}/${item.dataset}/labeled.csv
      params:
      - bohr.lock:
        - bohr_runtime_version
    foreach:
      all_heuristics_with_issues__berger_files:
        dataset: berger_files
        exp: all_heuristics_with_issues
        task: bugginess
      all_heuristics_with_issues__levin_files:
        dataset: levin_files
        exp: all_heuristics_with_issues
        task: bugginess
      all_heuristics_with_issues__manual_labels.herzig:
        dataset: manual_labels.herzig
        exp: all_heuristics_with_issues
        task: bugginess
      all_heuristics_with_issues__mauczka_files:
        dataset: mauczka_files
        exp: all_heuristics_with_issues
        task: bugginess
      refactoring_few_ref_heuristics__levin_files:
        dataset: levin_files
        exp: refactoring_few_ref_heuristics
        task: refactoring
      refactoring_few_ref_heuristics__manual_labels.herzig:
        dataset: manual_labels.herzig
        exp: refactoring_few_ref_heuristics
        task: refactoring
  TrainModel__all_heuristics_with_issues:
    always_changed: false
    cmd: bohr porcelain train-model all_heuristics_with_issues
    deps:
    - runs/bugginess/all_heuristics_with_issues/levin_files/heuristic_matrix.pkl
    metrics: []
    outs:
    - runs/bugginess/all_heuristics_with_issues/label_model.pkl
    - runs/bugginess/all_heuristics_with_issues/label_model_weights.csv
    params:
    - bohr.lock:
      - bohr_runtime_version
  TrainModel__refactoring_few_ref_heuristics:
    always_changed: false
    cmd: bohr porcelain train-model refactoring_few_ref_heuristics
    deps:
    - runs/refactoring/refactoring_few_ref_heuristics/levin_files/heuristic_matrix.pkl
    metrics: []
    outs:
    - runs/refactoring/refactoring_few_ref_heuristics/label_model.pkl
    - runs/refactoring/refactoring_few_ref_heuristics/label_model_weights.csv
    params:
    - bohr.lock:
      - bohr_runtime_version
